from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import gradio as gr

# Load the model and tokenizer
model_name = "deep0210/mistral-rag"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Move model to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Function to generate responses
def generate_response(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_length=100)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Gradio Chat Interface
def chatbot(input_text):
    response = generate_response(input_text)
    return response

# Create Gradio Interface with larger text boxes
iface = gr.Interface(
    fn=chatbot,  # Function to call
    inputs=gr.Textbox(lines=20, placeholder="Type your question here...", label="Input"),  # Larger input box
    outputs=gr.Textbox(lines=20, placeholder="Responses will genrate here...", label="Response"),  # Larger output box (automatically scrollable)
    title="LITE - AI",  # Title of the interface
    description="<center>LITE - AI Chat Interface Using A Light RAG Model Based on MISTRAL</center><br><br>"
                "<center><i>Note: The responses generated by this tool are not highly reliable, as the RAG model used is very light and has not been trained on extensive data. "
                "This tool is intended for educational and experimental purposes only and should not be used for professional or critical applications.</i></center>",
    examples=[
        "What is the capital of France?",
        "Explain quantum computing in simple terms.",
        "What is the difference between DNA and RNA?",
        "What is the speed of light?",
        "How does photosynthesis work?",
        "What is the Pythagorean theorem?",
        "Tell me about the history of the internet."
    ],# Example inputs
article="<center>Project created by <b>Deep Dey</b><br>"
            "<a href='https://github.com/Deep-Dey1' target='_blank'>GitHub</a> | "
            "<a href='https://www.linkedin.com/in/deepdey0210/' target='_blank'>LinkedIn</a></center>"
)

# Launch the interface
iface.launch()